import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Samuel's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative overflow-x-hidden antialiased ${geistSans.variable} ${geistMono.variable}`}
      >
        <Navbar />
        {children}
        <footer className="py-8 text-center bg-black text-gray-400">
          <p>
            © {new Date().getFullYear()} Samuel Rychvalský. All rights reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
