import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Samuel's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative bg-cover bg-no-repeat bg-fixed bg-center overflow-x-hidden antialiased ${geistSans.variable} ${geistMono.variable}`}
        style={{ backgroundImage: "url('/abstract.png')" }}
      >
        {children}
      </body>
    </html>
  );
}
